---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: crc-ocp-4.17.0-rc.5-arm64-
spec:
  pipelineRef:
    resolver: bundles 
    params:
    - name: bundle
      value: ghcr.io/crc-org/ci-snc-runner:pr-29-tkn
    - name: name
      value: snc-builder
    - name: kind
      value: pipeline
  
  params:
  - name: arch
    value: arm64
  - name: ocp-index-url
    value: https://mirror.openshift.com/pub/openshift-v4/arm64/clients/ocp/4.17.0-rc.5
  - name: snc-ref
    value: release-4.17
  - name: ocp-extended-cert
    value: enabled
  - name: debug
    value: 'true'
  workspaces:
    - name: storage
      persistentVolumeClaim:
        claimName: XXXXX
    - name: aws-credentials
      secret:
        secretName: XXXXX
    - name: rh-account-secret
      secret:
        secretName: XXXXX
    - name: ocp-pullsecret
      secret:
        secretName: XXXXX
  timeout: "8h"